import { lazy } from 'react';
import type { TemplateMeta } from './types';

export const DEFAULT_TEMPLATE = 'stripe-minimal';

export interface TemplateEntry extends TemplateMeta {
  component: React.LazyExoticComponent<React.ComponentType<any>>;
}

const registry: Record<string, TemplateEntry> = {
  'stripe-minimal': {
    slug: 'stripe-minimal',
    name: 'Stripe Minimal',
    description: 'Clean documentation style inspired by Stripe',
    font: 'Plus Jakarta Sans',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/01.png',
    defaultColors: { bg: '#ffffff', text: '#0a2540', accent: '#635bff' },
    component: lazy(() => import('./stripe-minimal/StripeMinimal')),
  },
  'linear-dashboard': {
    slug: 'linear-dashboard',
    name: 'Linear Dashboard',
    description: 'Sleek sidebar layout inspired by Linear',
    font: 'Inter',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/02.png',
    defaultColors: { bg: '#1a1a2e', text: '#e0e0e0', accent: '#5e6ad2' },
    component: lazy(() => import('./linear-dashboard/LinearDashboard')),
  },
  'vercel-dark': {
    slug: 'vercel-dark',
    name: 'Vercel Dark',
    description: 'Dark theme with sharp edges, inspired by Vercel',
    font: 'Inter',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/03.png',
    defaultColors: { bg: '#000000', text: '#ededed', accent: '#0070f3' },
    component: lazy(() => import('./vercel-dark/VercelDark')),
  },
  'notion-clean': {
    slug: 'notion-clean',
    name: 'Notion Clean',
    description: 'Minimal and content-focused like Notion',
    font: 'Outfit',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/04.png',
    defaultColors: { bg: '#ffffff', text: '#37352f', accent: '#2eaadc' },
    component: lazy(() => import('./notion-clean/NotionClean')),
  },
  'banking-corporate': {
    slug: 'banking-corporate',
    name: 'Banking Corporate',
    description: 'Professional corporate design for financial services',
    font: 'DM Sans',
    fontUrl: 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/05.png',
    defaultColors: { bg: '#f8f9fa', text: '#1a1a2e', accent: '#0d6efd' },
    component: lazy(() => import('./banking-corporate/BankingCorporate')),
  },
  'intercom-fresh': {
    slug: 'intercom-fresh',
    name: 'Intercom Fresh',
    description: 'Friendly and colorful help center style',
    font: 'Manrope',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/06.png',
    defaultColors: { bg: '#ffffff', text: '#1a1a1a', accent: '#5046e5' },
    component: lazy(() => import('./intercom-fresh/IntercomFresh')),
  },
  'editorial-grid': {
    slug: 'editorial-grid',
    name: 'Editorial Grid',
    description: 'Magazine-style grid layout with bold typography',
    font: 'Space Grotesk',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/07.png',
    defaultColors: { bg: '#fafafa', text: '#111111', accent: '#ff5722' },
    component: lazy(() => import('./editorial-grid/EditorialGrid')),
  },
  'swiss-minimal': {
    slug: 'swiss-minimal',
    name: 'Swiss Minimal',
    description: 'International typographic style with grid precision',
    font: 'Instrument Sans',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/08.png',
    defaultColors: { bg: '#ffffff', text: '#000000', accent: '#e63946' },
    component: lazy(() => import('./swiss-minimal/SwissMinimal')),
  },
  'glassmorphism-premium': {
    slug: 'glassmorphism-premium',
    name: 'Glassmorphism Premium',
    description: 'Frosted glass effects with premium feel',
    font: 'Sora',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/09.png',
    defaultColors: { bg: '#0f0f23', text: '#e2e8f0', accent: '#818cf8' },
    component: lazy(() => import('./glassmorphism-premium/GlassmorphismPremium')),
  },
  'startup-bold': {
    slug: 'startup-bold',
    name: 'Startup Bold',
    description: 'Vibrant and energetic startup aesthetic',
    font: 'Outfit',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/10.png',
    defaultColors: { bg: '#ffffff', text: '#1e293b', accent: '#7c3aed' },
    component: lazy(() => import('./startup-bold/StartupBold')),
  },
  'colorful-playful': {
    slug: 'colorful-playful',
    name: 'Colorful Playful',
    description: 'Bright and bouncy with playful animations',
    font: 'Nunito',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap',
    screenshotPath: '/wireframes/screenshots/11.png',
    defaultColors: { bg: '#FFF7ED', text: '#1F1F1F', accent: '#FF6B6B' },
    component: lazy(() => import('./colorful-playful/ColorfulPlayful')),
  },
  'retro-vintage': {
    slug: 'retro-vintage',
    name: 'Retro Vintage',
    description: 'VHS typewriter aesthetic with warm sepia tones',
    font: 'Space Mono',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap',
    screenshotPath: '/wireframes/screenshots/12.png',
    defaultColors: { bg: '#F5E6D0', text: '#2D1B0E', accent: '#D4651E' },
    component: lazy(() => import('./retro-vintage/RetroVintage')),
  },
  'brutalist-raw': {
    slug: 'brutalist-raw',
    name: 'Brutalist Raw',
    description: 'Ultra-bold borders, no radius, raw industrial feel',
    font: 'Space Grotesk',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;700&display=swap',
    screenshotPath: '/wireframes/screenshots/13.png',
    defaultColors: { bg: '#FFFFFF', text: '#000000', accent: '#FF0000' },
    component: lazy(() => import('./brutalist-raw/BrutalistRaw')),
  },
  'warm-earthy': {
    slug: 'warm-earthy',
    name: 'Warm Earthy',
    description: 'Terracotta and sage with organic serif elegance',
    font: 'Libre Baskerville',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap',
    screenshotPath: '/wireframes/screenshots/14.png',
    defaultColors: { bg: '#FAF5F0', text: '#3D2C1E', accent: '#C2774E' },
    component: lazy(() => import('./warm-earthy/WarmEarthy')),
  },
  'soft-pastel': {
    slug: 'soft-pastel',
    name: 'Soft Pastel',
    description: 'Dreamy pink, lavender and mint with cloud-like cards',
    font: 'Quicksand',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/15.png',
    defaultColors: { bg: '#FFF5F7', text: '#4A4A4A', accent: '#F9A8D4' },
    component: lazy(() => import('./soft-pastel/SoftPastel')),
  },
  'neon-cyberpunk': {
    slug: 'neon-cyberpunk',
    name: 'Neon Cyberpunk',
    description: 'Dark theme with neon glow effects and cyber aesthetic',
    font: 'Rajdhani',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/16.png',
    defaultColors: { bg: '#0A0A0F', text: '#E0E0E0', accent: '#00FF88' },
    component: lazy(() => import('./neon-cyberpunk/NeonCyberpunk')),
  },
  'luxury-gold': {
    slug: 'luxury-gold',
    name: 'Luxury Gold',
    description: 'Black and gold with shimmer animations and serif typography',
    font: 'Playfair Display',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800&display=swap',
    screenshotPath: '/wireframes/screenshots/17.png',
    defaultColors: { bg: '#0C0C0C', text: '#F5F5F5', accent: '#C9A84C' },
    component: lazy(() => import('./luxury-gold/LuxuryGold')),
  },
  'monochrome-elegant': {
    slug: 'monochrome-elegant',
    name: 'Monochrome Elegant',
    description: 'Sophisticated grayscale with print-inspired serif layout',
    font: 'Cormorant Garamond',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/18.png',
    defaultColors: { bg: '#F8F8F8', text: '#1A1A1A', accent: '#555555' },
    component: lazy(() => import('./monochrome-elegant/MonochromeElegant')),
  },
  'gradient-mesh': {
    slug: 'gradient-mesh',
    name: 'Gradient Mesh',
    description: 'Animated mesh gradients with glassmorphism cards',
    font: 'Poppins',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/19.png',
    defaultColors: { bg: '#FFFFFF', text: '#1E1E2E', accent: '#8B5CF6' },
    component: lazy(() => import('./gradient-mesh/GradientMesh')),
  },
  'zen-garden': {
    slug: 'zen-garden',
    name: 'Zen Garden',
    description: 'Japanese minimalism with generous whitespace and sage accents',
    font: 'Noto Serif JP',
    fontUrl: 'https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;500;600;700&display=swap',
    screenshotPath: '/wireframes/screenshots/20.png',
    defaultColors: { bg: '#FAF9F6', text: '#2C2C2C', accent: '#6B8E6B' },
    component: lazy(() => import('./zen-garden/ZenGarden')),
  },
};

export const templateList = Object.values(registry);

export default registry;
